branch(unacc, [_, _, _, _, _, safety/low]).
branch(unacc, [buying/low, maint/vhigh, _, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/high, doors/5more, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/high, doors/4, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/high, doors/3, persons/more, lug_boot/small, safety/med]).
branch(unacc, [buying/low, maint/high, doors/2, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/med, doors/5more, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/med, doors/4, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/med, doors/3, persons/more, lug_boot/small, safety/med]).
branch(unacc, [buying/low, maint/med, doors/2, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/low, doors/5more, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/low, doors/4, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/low, doors/3, persons/more, lug_boot/small, safety/med]).
branch(unacc, [buying/low, maint/low, doors/2, persons/more, lug_boot/small, safety/med]).
branch(unacc, [buying/med, maint/vhigh, _, persons/more, lug_boot/small, safety/med]).
branch(unacc, [buying/med, maint/high, _, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/med, maint/med, doors/5more, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/med, maint/med, doors/4, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/med, maint/med, doors/3, persons/more, lug_boot/small, safety/med]).
branch(unacc, [buying/med, maint/med, doors/2, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/med, maint/low, doors/5more, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/med, maint/low, doors/4, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/med, maint/low, doors/3, persons/more, lug_boot/small, safety/med]).
branch(unacc, [buying/med, maint/low, doors/2, persons/more, lug_boot/small, safety/med]).
branch(unacc, [buying/high, _, _, persons/more, lug_boot/small, safety/med]).
branch(unacc, [buying/vhigh, _, _, persons/more, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/vhigh, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/vhigh, doors/4, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/vhigh, doors/3, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/low, maint/vhigh, doors/2, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/high, _, persons/more, lug_boot/med, safety/med]).
branch(good, [buying/low, maint/med, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(good, [buying/low, maint/med, doors/4, persons/more, lug_boot/med, safety/med]).
branch(good, [buying/low, maint/med, doors/3, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/med, doors/2, persons/more, lug_boot/med, safety/med]).
branch(good, [buying/low, maint/low, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(good, [buying/low, maint/low, doors/4, persons/more, lug_boot/med, safety/med]).
branch(good, [buying/low, maint/low, doors/3, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/low, doors/2, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/vhigh, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/vhigh, doors/4, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/vhigh, doors/3, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/med, maint/vhigh, doors/2, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/high, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/high, doors/4, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/high, doors/3, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/med, maint/high, doors/2, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/med, _, persons/more, lug_boot/med, safety/med]).
branch(good, [buying/med, maint/low, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(good, [buying/med, maint/low, doors/4, persons/more, lug_boot/med, safety/med]).
branch(good, [buying/med, maint/low, doors/3, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/low, doors/2, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/high, maint/vhigh, _, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/high, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/high, doors/4, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/high, doors/3, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/high, maint/high, doors/2, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/med, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/med, doors/4, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/med, doors/3, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/high, maint/med, doors/2, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/low, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/low, doors/4, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/low, doors/3, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/high, maint/low, doors/2, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/vhigh, maint/vhigh, _, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/vhigh, maint/high, _, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/vhigh, maint/med, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/vhigh, maint/med, doors/4, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/vhigh, maint/med, doors/3, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/vhigh, maint/med, doors/2, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/vhigh, maint/low, doors/5more, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/vhigh, maint/low, doors/4, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/vhigh, maint/low, doors/3, persons/more, lug_boot/med, safety/med]).
branch(unacc, [buying/vhigh, maint/low, doors/2, persons/more, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/vhigh, _, persons/more, lug_boot/big, safety/med]).
branch(acc, [buying/low, maint/high, _, persons/more, lug_boot/big, safety/med]).
branch(good, [buying/low, maint/med, _, persons/more, lug_boot/big, safety/med]).
branch(good, [buying/low, maint/low, _, persons/more, lug_boot/big, safety/med]).
branch(acc, [buying/med, maint/vhigh, _, persons/more, lug_boot/big, safety/med]).
branch(acc, [buying/med, maint/high, _, persons/more, lug_boot/big, safety/med]).
branch(acc, [buying/med, maint/med, _, persons/more, lug_boot/big, safety/med]).
branch(good, [buying/med, maint/low, _, persons/more, lug_boot/big, safety/med]).
branch(unacc, [buying/high, maint/vhigh, _, persons/more, lug_boot/big, safety/med]).
branch(acc, [buying/high, maint/high, _, persons/more, lug_boot/big, safety/med]).
branch(acc, [buying/high, maint/med, _, persons/more, lug_boot/big, safety/med]).
branch(acc, [buying/high, maint/low, _, persons/more, lug_boot/big, safety/med]).
branch(unacc, [buying/vhigh, maint/vhigh, _, persons/more, lug_boot/big, safety/med]).
branch(unacc, [buying/vhigh, maint/high, _, persons/more, lug_boot/big, safety/med]).
branch(acc, [buying/vhigh, maint/med, _, persons/more, lug_boot/big, safety/med]).
branch(acc, [buying/vhigh, maint/low, _, persons/more, lug_boot/big, safety/med]).
branch(unacc, [buying/vhigh, maint/low, _, persons/4, lug_boot/small, safety/med]).
branch(acc, [buying/vhigh, maint/low, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/vhigh, maint/low, doors/4, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/vhigh, maint/low, doors/3, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/vhigh, maint/low, doors/2, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/vhigh, maint/low, _, persons/4, lug_boot/big, safety/med]).
branch(unacc, [buying/vhigh, maint/med, _, persons/4, lug_boot/small, safety/med]).
branch(acc, [buying/vhigh, maint/med, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/vhigh, maint/med, doors/4, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/vhigh, maint/med, doors/3, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/vhigh, maint/med, doors/2, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/vhigh, maint/med, _, persons/4, lug_boot/big, safety/med]).
branch(unacc, [buying/vhigh, maint/high, _, persons/4, _, safety/med]).
branch(unacc, [buying/vhigh, maint/vhigh, _, persons/4, _, safety/med]).
branch(unacc, [buying/high, maint/vhigh, _, persons/4, lug_boot/big, safety/med]).
branch(acc, [buying/high, maint/high, _, persons/4, lug_boot/big, safety/med]).
branch(acc, [buying/high, maint/med, _, persons/4, lug_boot/big, safety/med]).
branch(acc, [buying/high, maint/low, _, persons/4, lug_boot/big, safety/med]).
branch(unacc, [buying/high, _, doors/2, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/high, _, doors/3, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/low, doors/4, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/med, doors/4, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/high, doors/4, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/high, maint/vhigh, doors/4, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/low, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/med, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/high, maint/high, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/high, maint/vhigh, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/high, _, _, persons/4, lug_boot/small, safety/med]).
branch(acc, [buying/med, maint/low, _, persons/4, lug_boot/small, safety/med]).
branch(good, [buying/med, maint/low, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(good, [buying/med, maint/low, doors/4, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/low, doors/3, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/low, doors/2, persons/4, lug_boot/med, safety/med]).
branch(good, [buying/med, maint/low, _, persons/4, lug_boot/big, safety/med]).
branch(acc, [buying/med, maint/med, _, persons/4, _, safety/med]).
branch(unacc, [buying/med, maint/high, _, persons/4, lug_boot/small, safety/med]).
branch(acc, [buying/med, maint/high, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/high, doors/4, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/med, maint/high, doors/3, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/med, maint/high, doors/2, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/high, _, persons/4, lug_boot/big, safety/med]).
branch(unacc, [buying/med, maint/vhigh, _, persons/4, lug_boot/small, safety/med]).
branch(acc, [buying/med, maint/vhigh, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/vhigh, doors/4, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/med, maint/vhigh, doors/3, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/med, maint/vhigh, doors/2, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/med, maint/vhigh, _, persons/4, lug_boot/big, safety/med]).
branch(acc, [buying/low, maint/low, _, persons/4, lug_boot/small, safety/med]).
branch(good, [buying/low, maint/low, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(good, [buying/low, maint/low, doors/4, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/low, doors/3, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/low, doors/2, persons/4, lug_boot/med, safety/med]).
branch(good, [buying/low, maint/low, _, persons/4, lug_boot/big, safety/med]).
branch(acc, [buying/low, maint/med, _, persons/4, lug_boot/small, safety/med]).
branch(good, [buying/low, maint/med, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(good, [buying/low, maint/med, doors/4, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/med, doors/3, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/med, doors/2, persons/4, lug_boot/med, safety/med]).
branch(good, [buying/low, maint/med, _, persons/4, lug_boot/big, safety/med]).
branch(acc, [buying/low, maint/high, _, persons/4, _, safety/med]).
branch(unacc, [buying/low, maint/vhigh, _, persons/4, lug_boot/small, safety/med]).
branch(acc, [buying/low, maint/vhigh, doors/5more, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/vhigh, doors/4, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/low, maint/vhigh, doors/3, persons/4, lug_boot/med, safety/med]).
branch(unacc, [buying/low, maint/vhigh, doors/2, persons/4, lug_boot/med, safety/med]).
branch(acc, [buying/low, maint/vhigh, _, persons/4, lug_boot/big, safety/med]).
branch(unacc, [_, _, _, persons/2, _, safety/med]).
branch(acc, [buying/vhigh, maint/low, doors/2, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/vhigh, maint/low, doors/2, persons/more, lug_boot/med, safety/high]).
branch(unacc, [buying/vhigh, maint/low, doors/2, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/vhigh, maint/low, doors/3, persons/more, _, safety/high]).
branch(acc, [buying/vhigh, maint/low, doors/4, persons/more, _, safety/high]).
branch(acc, [buying/vhigh, maint/low, doors/5more, persons/more, _, safety/high]).
branch(acc, [buying/vhigh, maint/med, doors/2, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/vhigh, maint/med, doors/2, persons/more, lug_boot/med, safety/high]).
branch(unacc, [buying/vhigh, maint/med, doors/2, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/vhigh, maint/med, doors/3, persons/more, _, safety/high]).
branch(acc, [buying/vhigh, maint/med, doors/4, persons/more, _, safety/high]).
branch(acc, [buying/vhigh, maint/med, doors/5more, persons/more, _, safety/high]).
branch(unacc, [buying/vhigh, maint/high, _, persons/more, _, safety/high]).
branch(unacc, [buying/vhigh, maint/vhigh, _, persons/more, _, safety/high]).
branch(acc, [buying/high, maint/low, doors/2, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/high, maint/low, doors/2, persons/more, lug_boot/med, safety/high]).
branch(unacc, [buying/high, maint/low, doors/2, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/high, maint/low, doors/3, persons/more, _, safety/high]).
branch(acc, [buying/high, maint/low, doors/4, persons/more, _, safety/high]).
branch(acc, [buying/high, maint/low, doors/5more, persons/more, _, safety/high]).
branch(acc, [buying/high, maint/med, doors/2, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/high, maint/med, doors/2, persons/more, lug_boot/med, safety/high]).
branch(unacc, [buying/high, maint/med, doors/2, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/high, maint/med, doors/3, persons/more, _, safety/high]).
branch(acc, [buying/high, maint/med, doors/4, persons/more, _, safety/high]).
branch(acc, [buying/high, maint/med, doors/5more, persons/more, _, safety/high]).
branch(acc, [buying/high, maint/high, doors/2, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/high, maint/high, doors/2, persons/more, lug_boot/med, safety/high]).
branch(unacc, [buying/high, maint/high, doors/2, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/high, maint/high, doors/3, persons/more, _, safety/high]).
branch(acc, [buying/high, maint/high, doors/4, persons/more, _, safety/high]).
branch(acc, [buying/high, maint/high, doors/5more, persons/more, _, safety/high]).
branch(unacc, [buying/high, maint/vhigh, _, persons/more, _, safety/high]).
branch(good, [buying/med, maint/low, doors/5more, persons/more, lug_boot/small, safety/high]).
branch(good, [buying/med, maint/low, doors/4, persons/more, lug_boot/small, safety/high]).
branch(good, [buying/med, maint/low, doors/3, persons/more, lug_boot/small, safety/high]).
branch(unacc, [buying/med, maint/low, doors/2, persons/more, lug_boot/small, safety/high]).
branch(vgood, [buying/med, maint/low, doors/5more, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/med, maint/low, doors/4, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/med, maint/low, doors/3, persons/more, lug_boot/med, safety/high]).
branch(good, [buying/med, maint/low, doors/2, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/med, maint/low, _, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/med, maint/med, doors/5more, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/med, maint/med, doors/4, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/med, maint/med, doors/3, persons/more, lug_boot/small, safety/high]).
branch(unacc, [buying/med, maint/med, doors/2, persons/more, lug_boot/small, safety/high]).
branch(vgood, [buying/med, maint/med, doors/5more, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/med, maint/med, doors/4, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/med, maint/med, doors/3, persons/more, lug_boot/med, safety/high]).
branch(acc, [buying/med, maint/med, doors/2, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/med, maint/med, _, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/med, maint/high, doors/2, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/med, maint/high, doors/2, persons/more, lug_boot/med, safety/high]).
branch(unacc, [buying/med, maint/high, doors/2, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/med, maint/high, doors/3, persons/more, _, safety/high]).
branch(acc, [buying/med, maint/high, doors/4, persons/more, _, safety/high]).
branch(acc, [buying/med, maint/high, doors/5more, persons/more, _, safety/high]).
branch(acc, [buying/med, maint/vhigh, doors/2, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/med, maint/vhigh, doors/2, persons/more, lug_boot/med, safety/high]).
branch(unacc, [buying/med, maint/vhigh, doors/2, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/med, maint/vhigh, doors/3, persons/more, _, safety/high]).
branch(acc, [buying/med, maint/vhigh, doors/4, persons/more, _, safety/high]).
branch(acc, [buying/med, maint/vhigh, doors/5more, persons/more, _, safety/high]).
branch(good, [buying/low, maint/low, doors/5more, persons/more, lug_boot/small, safety/high]).
branch(good, [buying/low, maint/low, doors/4, persons/more, lug_boot/small, safety/high]).
branch(good, [buying/low, maint/low, doors/3, persons/more, lug_boot/small, safety/high]).
branch(unacc, [buying/low, maint/low, doors/2, persons/more, lug_boot/small, safety/high]).
branch(vgood, [buying/low, maint/low, doors/5more, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/low, doors/4, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/low, doors/3, persons/more, lug_boot/med, safety/high]).
branch(good, [buying/low, maint/low, doors/2, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/low, _, persons/more, lug_boot/big, safety/high]).
branch(good, [buying/low, maint/med, doors/5more, persons/more, lug_boot/small, safety/high]).
branch(good, [buying/low, maint/med, doors/4, persons/more, lug_boot/small, safety/high]).
branch(good, [buying/low, maint/med, doors/3, persons/more, lug_boot/small, safety/high]).
branch(unacc, [buying/low, maint/med, doors/2, persons/more, lug_boot/small, safety/high]).
branch(vgood, [buying/low, maint/med, doors/5more, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/med, doors/4, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/med, doors/3, persons/more, lug_boot/med, safety/high]).
branch(good, [buying/low, maint/med, doors/2, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/med, _, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/low, maint/high, doors/5more, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/low, maint/high, doors/4, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/low, maint/high, doors/3, persons/more, lug_boot/small, safety/high]).
branch(unacc, [buying/low, maint/high, doors/2, persons/more, lug_boot/small, safety/high]).
branch(vgood, [buying/low, maint/high, doors/5more, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/high, doors/4, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/high, doors/3, persons/more, lug_boot/med, safety/high]).
branch(acc, [buying/low, maint/high, doors/2, persons/more, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/high, _, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/low, maint/vhigh, doors/2, persons/more, lug_boot/big, safety/high]).
branch(acc, [buying/low, maint/vhigh, doors/2, persons/more, lug_boot/med, safety/high]).
branch(unacc, [buying/low, maint/vhigh, doors/2, persons/more, lug_boot/small, safety/high]).
branch(acc, [buying/low, maint/vhigh, doors/3, persons/more, _, safety/high]).
branch(acc, [buying/low, maint/vhigh, doors/4, persons/more, _, safety/high]).
branch(acc, [buying/low, maint/vhigh, doors/5more, persons/more, _, safety/high]).
branch(acc, [buying/vhigh, maint/low, _, persons/4, _, safety/high]).
branch(acc, [buying/vhigh, maint/med, _, persons/4, _, safety/high]).
branch(unacc, [buying/vhigh, maint/high, _, persons/4, _, safety/high]).
branch(unacc, [buying/vhigh, maint/vhigh, _, persons/4, _, safety/high]).
branch(acc, [buying/high, maint/low, _, persons/4, _, safety/high]).
branch(acc, [buying/high, maint/med, _, persons/4, _, safety/high]).
branch(acc, [buying/high, maint/high, _, persons/4, _, safety/high]).
branch(unacc, [buying/high, maint/vhigh, _, persons/4, _, safety/high]).
branch(good, [buying/med, maint/low, _, persons/4, lug_boot/small, safety/high]).
branch(vgood, [buying/med, maint/low, doors/5more, persons/4, lug_boot/med, safety/high]).
branch(vgood, [buying/med, maint/low, doors/4, persons/4, lug_boot/med, safety/high]).
branch(good, [buying/med, maint/low, doors/3, persons/4, lug_boot/med, safety/high]).
branch(good, [buying/med, maint/low, doors/2, persons/4, lug_boot/med, safety/high]).
branch(vgood, [buying/med, maint/low, _, persons/4, lug_boot/big, safety/high]).
branch(acc, [buying/med, maint/med, _, persons/4, lug_boot/small, safety/high]).
branch(vgood, [buying/med, maint/med, doors/5more, persons/4, lug_boot/med, safety/high]).
branch(vgood, [buying/med, maint/med, doors/4, persons/4, lug_boot/med, safety/high]).
branch(acc, [buying/med, maint/med, doors/3, persons/4, lug_boot/med, safety/high]).
branch(acc, [buying/med, maint/med, doors/2, persons/4, lug_boot/med, safety/high]).
branch(vgood, [buying/med, maint/med, _, persons/4, lug_boot/big, safety/high]).
branch(acc, [buying/med, maint/high, _, persons/4, _, safety/high]).
branch(acc, [buying/med, maint/vhigh, _, persons/4, _, safety/high]).
branch(good, [buying/low, maint/low, _, persons/4, lug_boot/small, safety/high]).
branch(vgood, [buying/low, maint/low, doors/5more, persons/4, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/low, doors/4, persons/4, lug_boot/med, safety/high]).
branch(good, [buying/low, maint/low, doors/3, persons/4, lug_boot/med, safety/high]).
branch(good, [buying/low, maint/low, doors/2, persons/4, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/low, _, persons/4, lug_boot/big, safety/high]).
branch(good, [buying/low, maint/med, _, persons/4, lug_boot/small, safety/high]).
branch(vgood, [buying/low, maint/med, doors/5more, persons/4, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/med, doors/4, persons/4, lug_boot/med, safety/high]).
branch(good, [buying/low, maint/med, doors/3, persons/4, lug_boot/med, safety/high]).
branch(good, [buying/low, maint/med, doors/2, persons/4, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/med, _, persons/4, lug_boot/big, safety/high]).
branch(acc, [buying/low, maint/high, _, persons/4, lug_boot/small, safety/high]).
branch(vgood, [buying/low, maint/high, doors/5more, persons/4, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/high, doors/4, persons/4, lug_boot/med, safety/high]).
branch(acc, [buying/low, maint/high, doors/3, persons/4, lug_boot/med, safety/high]).
branch(acc, [buying/low, maint/high, doors/2, persons/4, lug_boot/med, safety/high]).
branch(vgood, [buying/low, maint/high, _, persons/4, lug_boot/big, safety/high]).
branch(acc, [buying/low, maint/vhigh, _, persons/4, _, safety/high]).
branch(unacc, [_, _, _, persons/2, _, safety/high]).
